name: Deploy to GitHub pages
on:
  push:
    # this is the branch where you develop your site
    # as discussed in the publishing sources section
    # this can change if you are using an user/organization repo
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node_version: '18'

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
